# Numpy library


In [1]:
#importing numpy library
import numpy as np
n = np.array([1,2,3,4,5])
n

array([1, 2, 3, 4, 5])

In [2]:
type(n)

numpy.ndarray

# Multidimentional array

In [3]:
#Here there is an example of 3 dimentional array.
list_ = np.array([[1,2,3],[4,5,6],[7,8,9]])
list_

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
list_.shape # if we check the shape of array so it will be 3 columns and 3 rows(3,3).

(3, 3)

In [5]:
np.arange(0,11) # a range function works same as range function. It will give an output of number range from 0 to 10.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
for i in range(0,11):
    print(i)

0
1
2
3
4
5
6
7
8
9
10


In [7]:
zero = np.zeros(100)
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
a = np.eye(10)
a

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [10]:
RN = np.arange(0,101)
RN

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [11]:
len(RN)

101

In [12]:
num = np.linspace(1,7,10)
num

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        , 5.66666667, 6.33333333, 7.        ])

In [13]:
len(num)

10

In [14]:
num.resize(5,2) #once we resize the array will change as per the resize values. 

In [15]:
 num

array([[1.        , 1.66666667],
       [2.33333333, 3.        ],
       [3.66666667, 4.33333333],
       [5.        , 5.66666667],
       [6.33333333, 7.        ]])

In [16]:
n = np.linspace(1,10,12)

In [17]:
n

array([ 1.        ,  1.81818182,  2.63636364,  3.45454545,  4.27272727,
        5.09090909,  5.90909091,  6.72727273,  7.54545455,  8.36363636,
        9.18181818, 10.        ])

In [18]:
n.reshape(6,2)

array([[ 1.        ,  1.81818182],
       [ 2.63636364,  3.45454545],
       [ 4.27272727,  5.09090909],
       [ 5.90909091,  6.72727273],
       [ 7.54545455,  8.36363636],
       [ 9.18181818, 10.        ]])

In [19]:
#once we reshape the array it will change the array temporary. 
#If you want to save that then you need make a new variable and then assign the value.
new_n = n.reshape(6,2)
new_n

array([[ 1.        ,  1.81818182],
       [ 2.63636364,  3.45454545],
       [ 4.27272727,  5.09090909],
       [ 5.90909091,  6.72727273],
       [ 7.54545455,  8.36363636],
       [ 9.18181818, 10.        ]])

# Generate some random values

In [20]:
#It will generate random vales,if you don't save in variable it will keep changing.
np.random.rand(5,5)

array([[0.45535819, 0.09143349, 0.62973238, 0.98662937, 0.27674628],
       [0.72940788, 0.09805703, 0.49985123, 0.55615451, 0.06936169],
       [0.65088534, 0.35199692, 0.42761895, 0.76249686, 0.04331129],
       [0.82770382, 0.71681082, 0.28790872, 0.30228242, 0.76550244],
       [0.27004256, 0.9155111 , 0.93411262, 0.14408459, 0.39985739]])

In [21]:
# It will return a sample from the 'standard normal' distribution.
a = np.random.randn(5,5)
a

array([[-0.29752931, -1.0487719 ,  0.01828532, -0.14717767,  0.4590518 ],
       [-0.28409934,  1.19762625, -0.6924812 , -0.08935537,  1.15709033],
       [-0.01557493,  0.53806158, -1.89999351, -0.62704095,  1.75983276],
       [-0.24151677, -0.13176028,  0.68864405, -0.55318479, -1.93548306],
       [ 0.32711344, -0.38650518, -0.50457336,  1.34698998, -0.56487797]])

In [22]:
#It will generate a number from given values
b = np.random.randint(1,10,15)
b

array([6, 8, 1, 6, 8, 1, 4, 4, 1, 8, 9, 5, 6, 1, 5])

In [23]:
len(b)

15

In [24]:
b.reshape(3,5)

array([[6, 8, 1, 6, 8],
       [1, 4, 4, 1, 8],
       [9, 5, 6, 1, 5]])

In [25]:
#easy way to do it
c = np.random.randint(1,10,(4,5))
c

array([[6, 2, 2, 2, 7],
       [3, 3, 1, 3, 9],
       [2, 3, 2, 8, 7],
       [3, 4, 6, 3, 2]])

# Indexing and Slicing

In [26]:
d = np.random.randint(1,20,15)
d

array([19,  9,  9, 13,  9,  1,  9, 13,  5,  5,  3, 13, 16,  4,  5])

In [27]:
d[0]

19

In [28]:
d[-1]

5

In [29]:
d[:4]

array([19,  9,  9, 13])

In [30]:
d[3:]

array([13,  9,  1,  9, 13,  5,  5,  3, 13, 16,  4,  5])

In [31]:
d[10:-2]

array([ 3, 13, 16])

In [32]:
e = np.arange(64)
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [33]:
e.resize(8,8)

In [34]:
e

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [35]:
e[2,4]

20

In [36]:
e[7,1:6]

array([57, 58, 59, 60, 61])

In [37]:
e[2:]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [38]:
e[3:,3:]

array([[27, 28, 29, 30, 31],
       [35, 36, 37, 38, 39],
       [43, 44, 45, 46, 47],
       [51, 52, 53, 54, 55],
       [59, 60, 61, 62, 63]])

In [39]:
e[:3,:3]

array([[ 0,  1,  2],
       [ 8,  9, 10],
       [16, 17, 18]])

In [50]:
e[e<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [51]:
e<50

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [52]:
e[e>25]=25
e

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25]])

In [53]:
e[1:,4]

array([12, 20, 25, 25, 25, 25, 25])

# Create a copy of original dataset
    So by using this function we have created a copy of original dataset,so later we can do experimental work on that copied  dataset.


In [57]:

e_new_copy = e.copy()

In [58]:
e_new_copy

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25]])

In [59]:
e_new_copy[3,3]

25

In [60]:
e_new_copy[:3,:3]

array([[ 0,  1,  2],
       [ 8,  9, 10],
       [16, 17, 18]])

In [61]:
e_new_copy[e_new_copy > 5] = 10

In [62]:
e_new_copy

array([[ 0,  1,  2,  3,  4,  5, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10]])

In [63]:
e_new_copy[3:,3:]

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

# Numpy_Exercises
1. Import NumPy Library as np

2. Create an array of integers starting from 15 to 40 and store it in a variable called array1

2.1. Create a second array of integers starting from 10 until 25 and store it in a variable called array2

2.2. What is the difference between the two arrays?

3. Create an array of all even integers from 2 to 20 and name it even_aaray1

3.1. Create an array of all even integers from 34 to 42 and name it even_array2

3.2. Create a matrix of the two arrays using the stack function

4. Create a 6×6 matrix with values ranging from 0 to 36 and retrieve the intersection of the 3rd row and 2nd column

4.1. Create a 5×2 matrix from a standard normal distribution generated with python.

4.2. Retrieve the value intersecting the last row and the last column of your matrix

5. Using your matrix created at 4.1, calculate the following:

   a. minimum of the matrix

   b. maximum of the matrix

   c. standard deviation of the matrix

  d. variance of the matrix

  e. mean of the matrix

# Solution

In [104]:
#Import NumPy Library as np
import numpy as np 

In [67]:
#Create an array of integers starting from 15 to 40 and store it in a variable called array1
array1 = np.arange(15,40)

In [68]:
array1

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39])

In [71]:
#Create a second array of integers starting from 10 until 25 and store it in a variable called array2
array2 = np.arange(10,26)

In [72]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [73]:
#What is the difference between the two arrays?

# array1 will generate values from 15 to 39 and 40th value will be excluded because in python index start from 0.
# array2 will generate values from 10 to 25.

In [74]:
# Create an array of all even integers from 2 to 20 and name it even_aaray1
even_aaray1 = np.arange(2,20,2)
even_aaray1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [75]:
# Create an array of all even integers from 34 to 42 and name it even_array2
even_array2 = np.arange(34,42,2)
even_array2

array([34, 36, 38, 40])

In [82]:
# Create a matrix of the two arrays using the stack function
a = np.arange(1,4)
b = np.arange(4,7)

c = np.stack((a,b))

c

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
# Create a 6×6 matrix with values ranging from 0 to 36 and retrieve the intersection of the 3rd row and 2nd column
mat_6 = np.arange(0,36)
mat_6.resize(6,6)
mat_6

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [91]:
mat_6[3,2]

20

In [94]:
# Create a 5×2 matrix from a standard normal distribution generated with python.
std_nm = np.random.randn(5,2)
std_nm

array([[ 0.99055421, -0.5412457 ],
       [ 0.63611148, -0.41181944],
       [-0.58372223,  0.3874521 ],
       [ 0.43671237, -1.49937691],
       [-0.67254349,  0.82225769]])

In [96]:
# Retrieve the value intersecting the last row and the last column of your matrix
std_nm[-1,-1]

0.8222576922121065

In [97]:
#Using your matrix created at 4.1, calculate the following:
#     a. minimum of the matrix
#     b. maximum of the matrix
#     c. standard deviation of the matrix
#     d. variance of the matrix
#     e. mean of the matrix

In [99]:
#  a. minimum of the matrix
std_nm.min()

-1.4993769146323388

In [100]:
# b. maximum of the matrix
std_nm.max()

0.9905542112429928

In [101]:
# c. standard deviation of the matrix
std_nm.std()

0.7673019752720552

In [102]:
# d. variance of the matrix
std_nm.var()

0.5887523212563976

In [103]:
# e. mean of the matrix
std_nm.mean()

-0.043561990812213236